version: '3'

services:
  dummy-mysqldb-1:
    container_name: mysqldb-1
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.mysql/dummy-1:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DUMMY_PASSWORD_1}
    restart: always
    ports:
      - "3306:3306"
    networks:
      - app-network

  dummy-mysqldb-2:
    container_name: mysqldb-2
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.mysql/dummy-2:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DUMMY_PASSWORD_2}
    restart: always
    ports:
      - "3307:3306"
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge


    
